apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: naming-dev

namePrefix: dev-

nameSuffix: -dev

commonAnnotations:
  env: dev

patchesStrategicMerge:
- deployment-app.yaml