apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: naming-prod

namePrefix: prod-

nameSuffix: -prod

commonAnnotations:
  env: prod

patchesStrategicMerge:
- deployment-app.yaml